apiVersion: v1
kind: Secret
metadata:
  name: voxera-secrets
  namespace: voxera
type: Opaque
stringData:
  db-connection-string: "Host=postgres-svc;Port=5432;Database=voxera;Username=voxera;Password=CHANGE_ME"
  jwt-secret-key: "CHANGE_THIS_TO_A_VERY_LONG_RANDOM_SECRET_KEY_AT_LEAST_64_CHARS_LONG"
  redis-connection-string: "redis-svc:6379,password=CHANGE_ME"
  rabbitmq-password: "CHANGE_ME"
  openai-api-key: ""
